#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. config/options $1

cd $PKG_BUILD/

./configure --host=$TARGET_NAME \
            --build=$HOST_NAME \
            --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --enable-static \
--with-x11vnc \
--with-x \
--without-xkeyboard \
--without-xinerama \
--without-xrandr \
--without-xfixes \
--without-xdamage \
--without-xtrap \
--without-xrecord \
--without-fbpm \
--without-dpms \
--without-v4l \
--without-fbdev \
--without-uinput \
--without-macosx-native \
--without-crypt \
--without-crypto \
--without-ssl \
--without-avahi \
--with-jpeg \
--without-libz \
--with-zlib \
--without-gnutls \
--without-client-tls \

make
