#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. config/options $1

# wxWidgets fails to build with LTO
  strip_lto

cd $PKG_BUILD

# use our strip
sed -i 's|strip $(APPNAME)|$(STRIP) $(APPNAME)|' Main/Main.make

WX_ROOT=$(ls -d $ROOT/$BUILD/wxWidgets-*)
WX_BUILD_DIR=$WX_ROOT/wxrelease

# enable environment WX_CONFIGURE_FLAGS
sed -i 's|WX_CONFIGURE_FLAGS :=|WX_CONFIGURE_FLAGS +=|' Makefile

# make wxWidgets library
if [ ! -d "$WX_BUILD_DIR" ]; then
  WX_CONFIGURE_FLAGS="--host=$TARGET_NAME --build=$HOST_NAME" \
  make wxbuild \
         NOGUI=1 \
         WX_ROOT=$WX_ROOT \
         WX_BUILD_DIR=$WX_BUILD_DIR
fi

WX_LIBS=$($WX_BUILD_DIR/wx-config --libs)

# make truecrypt binary
make NOGUI=1 \
     WXSTATIC=1 \
     NOTEST=1 \
     NOASM=1 \
     PKCS11_INC=$ROOT/$PKG_DIR/pkcs11 \
     WX_ROOT=$WX_ROOT \
     WX_BUILD_DIR=$WX_BUILD_DIR \
     WX_CONFIG=$WX_BUILD_DIR/wx-config \
     WX_LIBS="$WX_LIBS -lrt"
