#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. config/options $1

TC_PKG="`echo $PKG_URL | sed 's%.*/\(.*\)$%\1%' | sed 's|%20| |g'`"
SRC_ARCHIVE=$(readlink -f $SOURCES/$1/$TC_PKG)

cd $BUILD

tar xzf "$SRC_ARCHIVE"  

mv ${PKG_NAME}-${PKG_VERSION}-source ${PKG_NAME}_${PKG_VERSION}
